resourcegroup_name="test-tfvm-rg"
ssh_username="kunhoko"
ssh_password="CitrixOnAzure1!"
vm_size="Standard_F2s"
managed_image_resourcegroup_name="test-imgrepo-rg"
managed_image_name="imgtestwithdatadisk"